### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by rsmease** [rsmease/ashai#1]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducers 
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Demo login available
- [x] Clear navigation paths for users 
- [x] User is bootstrapped 
- [x] User can login, logout, sign up

**Comment by s-pangburn** [comment]
- [x] All buttons should set `cursor: pointer` on hover
  + Same with your Github and LinkedIn links
- [x] "View Demo" should be "Demo Login" - just more clear for recruiters looking for what button to click.
- [x] The Demo Login button should be down next to the login button, preferably side-by-side
- [x] Demo Login should be available on both login and signup forms. Ask Jay if you're having trouble with this, I already asked him to do it as well and he also uses the simulated typing trick.
- [x] Very cool technical achievement that your login/signup button doesn't activate until the user satisfies all criteria, but also not very user-friendly. It wouldn't be immediately clear to a recruiter why the button is still grayed out when all the fields have been filled out (they won't realize it's because of the password length, for example) **Have the buttons active as soon as all fields have been filled with anything at all, if you're going to keep this feature**
  + That being said, you still need to display errors. I entered a username that didn't exist into the login form (and I could presumably use a username and email that was already taken for the sign up form) and no errors displayed at all.
  + The password should be at least 6 characters, not 7
  + When the button activates, if you press backspace, it stays activated, defeating the purpose. The fix I proposed would render this point moot anyway, but I figured you should be aware of it.
- [x] Sign up doesn't work. I get a `422: Unprocessable Entity`
- [x] I can't verify login if I can't sign up ¯\_(ツ)_/¯

**Comment by rsmease** [comment]
@s-pangburn Can you clarify what you mean by "The Demo Login button should be down next to the login button, preferably side-by-side". Do you mean on the splash page (where there are three buttons) or on the session pages?

**Comment by s-pangburn** [comment]
@rsmease I mean on the session pages. Your splash page is totally fine!

**Comment by rsmease** [comment]
@s-pangburn This should be ready for your final run through now.

**Comment by s-pangburn** [comment]
Okay! It's looking nice and polished, good work! One final, minor point:

- [ ] Going to a random url (`http://www.ashai.co/#/sdjkfksjfhksjfh`) should redirect to the login page (this should be easy to accomplish with a `<Switch>`

However, that aside, it's at a stage where I am more than comfortable signing off on this. Great job Ryan! Your project is looking really good at this stage!
