### ISSUE TITLE
Projects

### ISSUE THREAD

**Issue by rsmease** [rsmease/ashai#6]
- [x] Backend: model, controller, views
- [x] Redux cycle: ajax, actions, reducers
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Game of Thrones-related data (seeded manually)

**Comment by rsmease** [comment]
@s-pangburn Note that the default view for all the projects looks the same right now; it opens the project's unique task page, but these all look identical because I haven't built tasks yet.

**Comment by s-pangburn** [comment]
- [x] The description on the right side disappears when I click "Add Task"? Maybe it's just because nothing pops up in its place yet though, so this is probably fine.
- [x] At this stage, I should be able to create my own projects, as well as edit and delete them.
- [x] Editing should extend to any aspect of the project (naming, description, etc.)

The project view CSS looks good though, exceptionally well-polished! Nice work 👍

**Comment by rsmease** [comment]
@s-pangburn I now have all the CRUD actions available to projects in the sidebar. Hover over the items and you'll see the afforances. I need your guidance on two issues: 

- [x] Edit changes / New projects do not populate in the sidebar after updating/creating; I have to rerender the page with a refresh and then they're visible. this.forceUpdate() didn't seem to work.
- [x] When deleting a project, I'm not redirected to '/app', so the empty project page with the deleted data is still available. I would image that I should fix this by adding a .then(history.push("home")) chained to requestToDeleteProject() call. Is this the best approach? 

Please also add any other fixes that you think are needed.

**Comment by s-pangburn** [comment]
(Duplicated from Teams)
- [x] CRUD affordances should `cursor: pointer` on hover
- [x] Modal should close when you click outside of it

**Comment by s-pangburn** [comment]
Usually when a component isn't updating properly but does when you refresh the page it means that something has gone wrong in the process between where your team/project is being updated in the backend and where it gets passed back into the component on the frontend. This means you should look in one of three places:

- The thunk action's promise (ensure it dispatches to the reducer correctly)
- The reducer (ensure it updates the state correctly)
- The container (ensure it properly subscribes the component to the store)
  + In addition, if you're using a selector, make sure it is selecting properly as well.

These would be where you would start, but it could be anything in that second half of the Redux cycle, which makes this especially tricky to debug. If you're still having trouble, feel free to move on to tasks for now and I will assist you with debugging this first thing tomorrow.

**Comment by s-pangburn** [comment]
`history.push("/")` would probably be the simplest way to accomplish that, yes!

**Comment by rsmease** [comment]
@s-pangburn Everything's done here.

**Comment by rsmease** [comment]
@s-pangburn Also, please give me feedback on my search! It only searches users for now.

**Comment by s-pangburn** [comment]
Very nice! Have the default text in your search bar specify "Search for a User" (or something similar) instead of just "Search" so the functionality is clear. Also, the text should turn all-white on hover, since you're fading to a blue background (black on blue is a bit hard to read) 

It's a very beautiful interface, amazing job! 👍
